# -*- coding: utf-8 -*-
"""19-03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E3wmeZUdRAux89G6zcBRoVPn9HOY2H2H
"""

# 1. O Reflorestador (Loop com Acumulador)
# Em um mini-game de reflorestamento, o jogador deve plantar árvores até atingir
# uma meta de "Biomassa". Crie um programa que peça ao usuário a meta de biomassa
# (em unidades). Depois, use um while para ler sucessivamente o valor de biomassa
# de cada árvore plantada. O programa deve parar assim que a meta for atingida ou
# superada e exibir quantas árvores foram necessárias.

contador = 0
soma_bio = 0

meta_bio = int(input("Meta de biomassa (em unidades): "))

while True:
  contador += 1
  valor_bio = int(input(f"Biomassa da {contador}a árvore: "))
  soma_bio += valor_bio
  if soma_bio >= meta_bio:
    break

print(f"Foram necessárias {contador} árvores para atingir a meta de biomassa.")

# 2. Simulador de Combate: Turnos de RPG
# Em um jogo de turno, um herói tem 100 de HP e enfrenta um monstro com 100 de HP.
# O programa deve pedir ao usuário o dano do ataque do herói e o dano do ataque do
# monstro por rodada. Use um while que continue enquanto ambos estiverem com HP
# acima de zero. Ao final de cada turno, mostre o HP restante de ambos. Se alguém
# chegar a 0, encerre e anuncie o vencedor.

vida_heroi = 100
vida_monstro = 100

while vida_heroi > 0 and vida_monstro > 0:
  print(f"Vida do herói: {vida_heroi}")
  print(f"Vida do monstro: {vida_monstro}")

  dano_heroi = int(input("Dano do ataque do herói: "))
  dano_monstro = int(input("Dano do ataque do monstro: "))

  vida_heroi -= dano_monstro
  vida_monstro -= dano_heroi

if (vida_heroi > 0):
  print("O herói venceu!")
else:
  print("O monstro venceu!")

# 3. Monitor de Inundação (Sentinela)
# Você está desenvolvendo um sistema de alerta para uma Smart City. O programa
# deve ler o nível do rio (em metros) continuamente.

# * Se o nível for menor que 3m: "Estado Normal".
# * Entre 3m e 5m: "Estado de Alerta".
# * Acima de 5m: "Evacuação Imediata".
# O programa só deve encerrar a leitura se o usuário digitar um valor negativo
# (flag/bandeira de encerramento).

while True:
  nivel_rio = int(input("Nível do rio (em metros): "))
  if nivel_rio < 0:
    print("Encerrando...")
    break
  elif nivel_rio < 3:
    print("Estado Normal")
  elif nivel_rio >= 3 and nivel_rio <= 5:
    print("Estado de Alerta")
  else:
    print("Evacuação Imediata")

# 4. O Coletor de Itens e Inventário
# Em um jogo de exploração, o jogador tem uma mochila com capacidade máxima de
# 15kg. Crie um programa que peça o peso de cada item encontrado no cenário, um
# por um. O while deve permitir a entrada de itens enquanto o peso total não
# ultrapassar 15kg. Se um item ultrapassar o limite, o programa deve avisar
# "Mochila cheia, item descartado" e encerrar, mostrando o peso final total.

peso_total = 0

while peso_total < 15:
  peso_item = float(input("Peso do item (em kg): "))
  peso_total += peso_item
  if peso_total > 15:
    print("Mochila cheia, item descartado")
    break

# 5. Média de Temperatura Global
# Para um painel informativo sobre mudanças climáticas, você precisa calcular a
# média de temperatura de um período. O usuário deve informar quantos dias deseja
# analisar. Use o while para ler a temperatura de cada um desses dias. Ao final,
# o programa deve exibir a média aritmética das temperaturas e informar se a
# média está "Acima do esperado" (caso seja maior que 25°C) ou
# "Dentro da normalidade".

soma_temp = 0
contador = 0
qtd_dias = int(input("Quantidade de dias: "))

while True:
  temp = float(input("Temperatura do dia: "))
  soma_temp += temp
  contador += 1

media = soma_temp / contador
print(f"Média de temperatura: {media}")
if media > 25:
  print("Temperatura acima do esperado")
else:
  print("Temperatura dentro da normalidade")